name: qr_code_bootstrap_channel
description: A QR-code bootstrap channel implementation.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  venice_core:
    git:
      url: https://github.com/Venice-D2D/venice_core.git
      tag_pattern: v{{version}}
    version: 0.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
