name: qr_code_bootstrap_channel
description: A QR-code bootstrap channel implementation.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  venice_core:
    git: https://github.com/Venice-D2D/venice_core.git
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
